/**
 * @file test_client.cpp
 * @brief Unit tests for Client class
 */

#include <chrono>
#include <thread>

#include "rollingraft/client.h"

#include <gtest/gtest.h>

using namespace rollingraft;

/**
 * Client tests.
 *
 * These tests verify the high-level client behavior.
 * Note: Tests requiring real servers are marked as integration tests.
 */

class ClientTest : public ::testing::Test {
 protected:
  void SetUp() override {
    // Use invalid addresses for basic tests
    servers_ = {"127.0.0.1:59991", "127.0.0.1:59992", "127.0.0.1:59993"};
  }

  std::vector<std::string> servers_;
};

// ========== Construction Tests ==========

TEST_F(ClientTest, Constructor_WithDefaultOptions) {
  Client client(servers_);
  EXPECT_GT(client.GetClientId(), 0);
}

TEST_F(ClientTest, Constructor_WithCustomOptions) {
  ClientOptions options;
  options.max_retries = 5;
  options.client_id = 12345;

  Client client(servers_, options);
  EXPECT_EQ(client.GetClientId(), 12345);
}

TEST_F(ClientTest, Constructor_EmptyServersList) {
  // Should handle empty list (will fail on first operation)
  std::vector<std::string> empty_servers;
  Client client(empty_servers);

  // Client is constructed but operations will fail
  EXPECT_GT(client.GetClientId(), 0);
}

TEST_F(ClientTest, MoveConstructor_TransfersOwnership) {
  Client client1(servers_);
  uint64_t client_id = client1.GetClientId();

  Client client2(std::move(client1));
  EXPECT_EQ(client2.GetClientId(), client_id);
}

TEST_F(ClientTest, MoveAssignment_TransfersOwnership) {
  Client client1(servers_);
  uint64_t client_id = client1.GetClientId();

  Client client2({"127.0.0.1:50000"});
  client2 = std::move(client1);
  EXPECT_EQ(client2.GetClientId(), client_id);
}

// ========== Initial State Tests ==========

TEST_F(ClientTest, GetLeaderAddr_InitiallyEmpty) {
  Client client(servers_);
  EXPECT_EQ(client.GetLeaderAddr(), "");
}

TEST_F(ClientTest, IsHealthy_NoServers_ReturnsFalse) {
  Client client(servers_);
  // No servers are running
  EXPECT_FALSE(client.IsHealthy());
}

// ========== Options Tests ==========

TEST_F(ClientTest, Options_CustomRetryCount) {
  ClientOptions options;
  options.max_retries = 0;  // No retries

  Client client(servers_, options);
  // Client created, operations will fail fast
  (void)client;
}

TEST_F(ClientTest, Options_CustomTimeout) {
  ClientOptions options;
  options.request_timeout = std::chrono::milliseconds(100);

  Client client(servers_, options);
  (void)client;
}

TEST_F(ClientTest, Options_LeaderCacheTTL) {
  ClientOptions options;
  options.leader_cache_ttl = std::chrono::milliseconds(500);

  Client client(servers_, options);
  (void)client;
}

// ========== RefreshLeader Tests ==========

TEST_F(ClientTest, RefreshLeader_ClearsCachedLeader) {
  Client client(servers_);

  // Initially empty
  EXPECT_EQ(client.GetLeaderAddr(), "");

  // Refresh doesn't crash
  client.RefreshLeader();

  // Still empty (no successful operation)
  EXPECT_EQ(client.GetLeaderAddr(), "");
}

// ========== Execute/Query Tests (without server) ==========

TEST_F(ClientTest, Execute_NoServersAvailable_ReturnsError) {
  ClientOptions options;
  options.max_retries = 1;
  options.request_timeout = std::chrono::milliseconds(50);

  Client client(servers_, options);

  auto result = client.Execute("test command");
  EXPECT_FALSE(result.ok());
  EXPECT_TRUE(result.has_error());
}

TEST_F(ClientTest, Query_NoServersAvailable_ReturnsError) {
  ClientOptions options;
  options.max_retries = 1;
  options.request_timeout = std::chrono::milliseconds(50);

  Client client(servers_, options);

  auto result = client.Query("test query");
  EXPECT_FALSE(result.ok());
  EXPECT_TRUE(result.has_error());
}

TEST_F(ClientTest, Execute_WithCustomTimeout_ReturnsError) {
  Client client(servers_);

  auto result = client.Execute("test", std::chrono::milliseconds(10));
  EXPECT_FALSE(result.ok());
}

// ========== ClientId Tests ==========

TEST_F(ClientTest, ClientId_AutoGenerated_IsUnique) {
  Client client1(servers_);
  Client client2(servers_);

  EXPECT_NE(client1.GetClientId(), client2.GetClientId());
}

TEST_F(ClientTest, ClientId_CustomId_Preserved) {
  ClientOptions options;
  options.client_id = 99999;

  Client client(servers_, options);
  EXPECT_EQ(client.GetClientId(), 99999);
}

// ========== Retry Behavior Tests ==========

TEST_F(ClientTest, Execute_WithZeroRetries_FailsFast) {
  ClientOptions options;
  options.max_retries = 0;
  options.request_timeout = std::chrono::milliseconds(50);

  Client client(servers_, options);

  auto start = std::chrono::steady_clock::now();
  auto result = client.Execute("test");
  auto elapsed = std::chrono::steady_clock::now() - start;

  EXPECT_FALSE(result.ok());
  // Should fail fast without retry delays
  EXPECT_LT(elapsed, std::chrono::milliseconds(1000));
}

// ========== Timeout Tests ==========

TEST_F(ClientTest, Execute_RespectsOverallTimeout) {
  ClientOptions options;
  options.max_retries = 10;  // Many retries
  options.request_timeout = std::chrono::milliseconds(100);

  Client client(servers_, options);

  auto start = std::chrono::steady_clock::now();
  // Overall timeout of 200ms - should stop before all retries
  auto result = client.Execute("test", std::chrono::milliseconds(200));
  auto elapsed = std::chrono::steady_clock::now() - start;

  EXPECT_FALSE(result.ok());
  // Should respect the shorter overall timeout
  EXPECT_LT(elapsed, std::chrono::milliseconds(1000));
}

// ========== Destructor Tests ==========

TEST_F(ClientTest, Destructor_NoPendingOperations) {
  {
    Client client(servers_);
    // No async operations
  }

  // If we get here without crash, destructor handled it correctly
  SUCCEED();
}
